const STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  BLOCKED: "BLOCKED",
  DELETED: "DELETED",
};

const BUSINESS_STATUS = {
  ACTIVE: "ACTIVE",
  PROSPECT: "PROSPECT",
  LEAD: "LEAD",
};

const CONTACT_STATUS = {
  ACTIVE: "ACTIVE",
  PROSPECT: "PROSPECT",
  CONVERTED: "CONVERTED",
  LEAD: "LEAD",
};

const REQUEST_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  PENDING_APPROVAL: "PENDING_APPROVAL"
};

module.exports = { 
  STATUS, 
  BUSINESS_STATUS,
  CONTACT_STATUS,
  REQUEST_STATUS
};
