const STATUS = {
  ASSIGNED: "ASSIGNED",
  UNASSIGNED: "UNASSIGNED"
};

const CONTACT_STATUS = {
  ACTIVE: "ACTIVE",
  PROSPECT: "PROSPECT",
  CONVERTED: "CONVERTED",
  LEAD: "LEAD",
  COMPLETED: "COMPLETED",
  NOT_COMPLETE: "NOT_COMPLETE"
};

const REQUEST_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  PENDING_APPROVAL: "PENDING_APPROVAL"
};

module.exports = { 
  STATUS, 
  CONTACT_STATUS,
  REQUEST_STATUS
};
